FONT_FAMILY = "Segoe UI"


TITLE = (FONT_FAMILY, 22, "bold")
SUBTITLE = (FONT_FAMILY, 14)
BODY = (FONT_FAMILY, 10)
BODY_BOLD = (FONT_FAMILY, 10, "bold")


CARD_VALUE = (FONT_FAMILY, 20, "bold")
CARD_TITLE = (FONT_FAMILY, 10)
